name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: fail
      run: fail
    
    - name: action-slack
      uses: 8398a7/action-slack@v2.4.2
      with:
        status: ${{ job.status }}
        username: ${{ github.workflow }}
        icon_url: https://emoji.slack-edge.com/T052RR32G/octocat/627964d7c9.png
        channel: notification-test  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }} # required
      if: always() # Pick up events even if the job fails or is canceled.
      
